server:
  # 配置端口
  port: 12388
  servlet:
    session:
      timeout: 21600
  address: 0.0.0.0

spring:
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ZERO_MYSQL_HOST:localhost}:${ZERO_MYSQL_PORT:3306}/zero?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: ${ZERO_MYSQL_USER:zero}
    password: ${ZERO_MYSQL_PWD:zero123456}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lingdeqin.zero.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

zero:
  author: 'Zero'
  title: '负二分之一自旋'
  desc: '转益多师是吾师'
  copyright: 'Copyright©2023 Zero'
  record-no: '备案号'
  github: 'https://github.com/lingdeqin'


